title: Late Bloomer
description: Wooyong's blog

url: http://yilmajung.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Blog
    url: /blog

social:
  github: yilmajung
  email: woo.firstrunner@gmail.com
  linkedin: Wooyong Jung

google_analytics: "UA-58263416-1"

disqus:
    shortname: my-disqus-shortname
